[tool.poetry]
name = "classy_config"
version = "0.1.6"
description = "Inject your config variables into methods, so they are as close to usage as possible."
readme = "README.md"
repository = "https://github.com/GDWR/classy-config"
authors = ["GDWR <gregory.dwr@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6.2"
pydantic = "^1.9.0"
typing-inspect = "^0.7.1"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
flake8 = "^4.0.1"
Sphinx = "^4.3.2"
sphinx-rtd-theme = "^1.0.0"
sphinxcontrib-napoleon = "^0.7"
flake8-annotations = "^2.7.0"
flake8-bandit = "^2.1.2"
flake8-bugbear = "^22.1.11"
flake8-docstrings = "^1.6.0"
flake8-import-order = "^0.18.1"
flake8-string-format = "^0.3.0"
pep8-naming = "^0.12.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
