[tool.poetry]
name = "classy_config"
version = "0.1.2"
description = "Inject your config variables into methods, so they are as close to usage as possible."
readme = "README.md"
repository = "https://github.com/GDWR/classy-config"
authors = ["GDWR <gregory.dwr@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6.1"
pydantic = "^1.9.0"
typing-inspect = "^0.7.1"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
flake8 = "^4.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
